version: "3.9"
services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - code-server

  code-server:
    image: codercom/code-server:latest
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD}
    volumes:
      - ./workspace:/home/coder/project
      - ./code-server-data:/home/coder/.local/share/code-server
      - ./code-server-config:/home/coder/.config/code-server
    command: ["--auth","password","--bind-addr","0.0.0.0:8080","/home/coder/project"]
    expose:
      - "8080"
